### ISSUE TITLE
test the close-up image by Jaime

### ISSUE THREAD

**Issue by yangf6** [jheissb/W251---Final-project-Weight-watchers#14]

**Comment by karenliangjw** [comment]
tested with image provided. Jaime's BMI prediction is 24.6 and 24.7 (I took two screenshot - the previous prediction is further from the face and the latter one is closer) where his actual BMI is 25.5. Also tested with Jaime's son but the result is bit off. Predicted value: 24 and actual is 17.5. Also tested with Leonardo Dicaprio's image I got from online. Prediction is 23.7 and actual (based on online stats) is 23.1. I'd say it's good enough for now. But I'd like to include more variance in training set. Will add another issue and start working on it this week.
